apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: clamav
  labels:
    name: clamav
spec:
  replicas: 3
  selector:
    matchLabels:
      name: clamav
  template:
    metadata:
      labels:
        name: clamav
    spec:
      volumes:
      - name: avdata
        emptyDir: {}
      - name: secrets
        emptyDir: {}
      containers:
      - name: vault-side-kick
        image: quay.io/ukhomeofficedigital/vault-sidekick:v0.2.0
        imagePullPolicy: Always
        resources:
         limits:
          memory: "100Mi"
          cpu: 100m
         requests:
          memory: "50Mi"
          cpu: 100m
        args:
          - -output=/etc/secrets
          - -tls-skip-verify=true
          - -cn=pki:services/${NAMESPACE}/pki/issue/default:common_name=clamav.${NAMESPACE}.svc.cluster.local,file=/etc/secrets/nginx,fmt=cert 
        env:
        - name: VAULT_ADDR
          value: "https://vault.vault.svc.cluster.local:8200"
        - name: VAULT_TOKEN
          valueFrom:
            secretKeyRef:
              name: store-token
              key: token
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
          - mountPath: /etc/secrets
            name: secrets
      - name: nginx
        image: quay.io/ukhomeofficedigital/nginx-proxy:v1.7.0
        imagePullPolicy: Always
        env:
          - name: PROXY_SERVICE_HOST
            value: 'http://127.0.0.1'
          - name: PROXY_SERVICE_PORT
            value: '8080'
          - name: NAXSI_USE_DEFAULT_RULES
            value: 'FALSE'
          - name: ENABLE_UUID_PARAM
            value: 'FALSE'
          - name: CLIENT_MAX_BODY_SIZE
            value: '10'
          - name: SSL_CERT
            value: /etc/secrets/nginx.crt
          - name: SSL_KEY
            value: /etc/secrets/nginx.key
        ports:
         - name: https
           containerPort: 443
        resources:
         limits:
          cpu: 100m
          memory: 400M
        volumeMounts:
          - mountPath: /etc/secrets
            name: secrets
      - name: clamd-rest
        image: quay.io/ukhomeofficedigital/clamav-rest:${.DRONE_COMMIT_SHA}
        imagePullPolicy: Always
        env:
        - name: HOST
          value: localhost
        - name: PORT
          value: '3310'
        ports:
        - containerPort: 8080
          name: api
          protocol: TCP    
        readinessProbe:
          exec:
            command:
            - /healthcheck.sh
          initialDelaySeconds: 60
          timeoutSeconds: 2
        readinessProbe:
          exec:
            command:
            - /healthcheck.sh
          initialDelaySeconds: 60
          timeoutSeconds: 2
        resources:
         limits:
          cpu: 200m
          memory: 800M
      - name: clamd
        image: quay.io/ukhomeofficedigital/clamav:${.DRONE_COMMIT_SHA}
        imagePullPolicy: Always
        ports:
        - containerPort: 3310
          name: api
          protocol: TCP
        volumeMounts:
          - mountPath: /var/lib/clamav
            name: avdata
        livenessProbe:
          exec:
            command:
            - /readyness.sh
          initialDelaySeconds: 50
          timeoutSeconds: 2
        readinessProbe:
          exec:
            command:
            - /readyness.sh
          initialDelaySeconds: 50
          timeoutSeconds: 2
        resources:
         limits:
          cpu: 200m
          memory: 400M
